import './globals.css'
import { Inter } from 'next/font/google'
import Provider from "@/app/provider";
import Head from "next/head";
import {Wrapper} from "@/app/wrapper";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.css" rel="stylesheet" />
    </Head>
      <body className={inter.className}>
      <Provider>
        <Wrapper  children={children}>
        </Wrapper>
      </Provider>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js"></script>
      </body>
    </html>
  )
}
